<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\apple.png" />
    <None Remove="images\avocado.png" />
    <None Remove="images\banana.png" />
    <None Remove="images\cherry.png" />
    <None Remove="images\dragon.png" />
    <None Remove="images\GoldHeart.png" />
    <None Remove="images\GoldHeart.svg" />
    <None Remove="images\grapes.png" />
    <None Remove="images\heart.png" />
    <None Remove="images\orange.png" />
    <None Remove="images\Strawberry.png" />
    <None Remove="sounds\background.mp3" />
    <None Remove="sounds\background.wav" />
    <None Remove="sounds\catch.wav" />
    <None Remove="sounds\gameOver.wav" />
    <None Remove="sounds\heart.mp3" />
    <None Remove="sounds\heart.wav" />
    <None Remove="sounds\miss.mp3" />
    <None Remove="sounds\miss.wav" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sounds\background.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sounds\catch.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sounds\gameOver.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sounds\heart.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sounds\heart.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sounds\miss.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sounds\reward.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Styles\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\apple.png" />
    <Resource Include="images\avocado.png" />
    <Resource Include="images\banana.png" />
    <Resource Include="images\cherry.png" />
    <Resource Include="images\dragon.png" />
    <Resource Include="images\grapes.png" />
    <Resource Include="images\heart.png" />
    <Resource Include="images\orange.png" />
    <Resource Include="images\Strawberry.png" />
  </ItemGroup>

</Project>
